### ISSUE TITLE
Installer.msi doesn't run

### ISSUE THREAD

**Issue by daryllabar** [josephmcmac/XRM-Developer-Tool#160] opened 2019-07-19 16:12 UTC
I'm attempting to run the JosephM.Dynamics365DevApp.Installer.msi.  When I do, a little box pops up, and then disappears.  Nothing appears to have happened...

**Comment by josephmcmac** [comment] 2019-07-19 21:59
> I'm attempting to run the JosephM.Dynamics365DevApp.Installer.msi. When I do, a little box pops up, and then disappears. Nothing appears to have happened...

Hi @daryllabar 

The installer for this application is a standard Microsoft installer package so any failure of it is not related specifically to my code. I have never had issues with it and unsure what has been conjured up to prevent it working

If I was you and had this issue I would do these things
- Verify at least .NET 4.6.1 is installed on your machine. This is the max .NET version used
- Verify if running the installer as an admin works
- Check the event viewer log for the error details. If the installer fails it should log details of the fatal error there
- If neither of the above found a resolution, then run the app in visual studio. The code is all open source in this repository so you could just clone the repository and run it in the IDE. This would avoid the need for the installer to run

**Comment by phuocle** [comment] 2019-07-20 00:26
wowwo

@daryllabar found this repos !😊

**Comment by daryllabar** [comment] 2019-07-20 03:32
@phuocle why has no one mentioned it to me before?  Why isn't it featured on the XrmToolCast?

**Comment by josephmcmac** [comment] 2019-07-22 22:35
@daryllabar closing this issue as I don't think the problem is related to the code

If you are still having issue and want to run the app let me know and I could link you though the executables which don't require the installer

**Closed by josephmcmac** 2019-07-22 22:35 UTC
